### PR TITLE
Use phpcs for tests dir

### PR DESCRIPTION
**Pull request by scaytrase**
Applies phpcs to test files on a regular basis

### CODE REVIEW

**Comment by scaytrase** [comment]
@lezhnev74 what about this one?

**Comment by lezhnev74** [comment]
This PR forces tests to conform to Doctrine coding standards. 
Since I did not develop tests with that checks in mind, I might need to refactor all of them to conform to the Doctrine rules.

In general, tests should be of as high quality as possible, as well as the code itself.

**Comment by scaytrase** [comment]
i've applied phpcbf here, is it not enough?

**Comment by lezhnev74** [comment]
Try to run this command:
`./vendor/bin/phpcs`

This is what I see: 
image

`phpcbf` can fix only so much problems. Some code style issues are solvable by hands.

**Updated**
I am looking at the `phpcs` report. There are mostly just two error types:
1. missing visibility identifier
2. names are not camel caps. `test_it_validates_maxItems_green` => `testItValidatesMaxItemsGreen`

**Comment by scaytrase** [comment]
> This is what I see:

Ah, I see. In our team we use [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) which fix all the things it considered violated, but I'm afraid there is no csc set for doctrine ruleset

> I am looking at the phpcs report. There are mostly just two error types:

I can update all of them by hand in this PR

**Comment by lezhnev74** [comment]
That would a hell of the PR. If you can do this, please go ahead 🥇

**Comment by scaytrase** [comment]
I've added cscheck as separate travis step, so we can track the progress now

https://travis-ci.org/lezhnev74/openapi-psr7-validator/jobs/533693779

**Comment by scaytrase** [comment]
I'm utilized https://plugins.jetbrains.com/plugin/7160-camelcase for the rest ) 5 errors left to fix

**Comment by scaytrase** [comment]
Aaand all green!

**Comment by scaytrase** [comment]
Dont know why, but locally it show more progress-bar points

```
PS C:\Work\Projects\lezhnev74\openapi-psr7-validator> vendor/bin/phpcs --no-colors
............................................................  60 / 125 (48%)
............................................................ 120 / 125 (96%)
.....                                                        125 / 125 (100%)
```

Travis show the same count as your screenshot above. But I hope this does not influence anything

**Comment by lezhnev74** [comment]
Great work!!!

> Dont know why, but locally it show more progress-bar points

That is interesting.

**Pull request merged**
